[package]
edition = "2021"
rust-version = "1.60"
version = "0.1.0-alpha.1"
license = "Apache-2.0"
resolver = "2"
name = "capnp-models"
build = "src/build.rs"

[dependencies]
capnp = "0.18.10"

[build-dependencies]
capnpc = "0.18.0"

[lib]
crate-type = ["cdylib", "lib"]